server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      orders: orders
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
